kubewarden/kwctl

Cargo.lock
Cargo.toml
src/main.rs
src/policies.rs
src/pull.rs
src/run.rs

Fixes: https://github.com/kubewarden/kwctl/issues/1
Fixes: https://github.com/kubewarden/kwctl/issues/11
The interface looks as follows:
```
USAGE:
kwctl <SUBCOMMAND>
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
SUBCOMMANDS:
help        Prints this message or the help of the given subcommand(s)
policies    Lists all downloaded policies
pull        Pulls a Kubewarden policy from a given URI
run         Runs a Kubewarden policy from a given URI
```

feature: implement basic feature set and CLI interface

---

Cargo.lock
Cargo.toml
e2e-tests/e2e.bats
src/main.rs
src/rm.rs

Implement the `rm` command that allows a user to remove a cached
policy, previously downloaded from an OCI registry or an HTTP server.
Fixes https://github.com/kubewarden/kwctl/issues/9

feature: implement policy store removal

---

e2e-tests/e2e.bats
e2e-tests/test-data/privileged-pod-admission-review.json
e2e-tests/test-data/unprivileged-pod-admission-review.json
src/run.rs

Now it's possible to pass the toplevel `AdmissionReview` object to the
request path of kwctl, or the inner `request` attribute of it. Both
will be interpreted by kwctl and forwarded to the policy to evaluate.
Fixes https://github.com/kubewarden/kwctl/issues/10

Allow to pass AdmissionReview directly as the request object

---

Cargo.lock
Cargo.toml
src/annotate.rs
src/constants.rs
src/inspect.rs
src/main.rs

Introduce the `annotate` and the `inspect` commands.
Fixes https://github.com/kubewarden/kwctl/issues/8
```console
$ kwctl annotate
-m ../psp-apparmor/metadata.yml \
-o annotated.wasm \
../psp-apparmor/target/wasm32-unknown-unknown/release/psp_apparmor.wasm
```
This command reads the user-provided metadata file, reads a vanilla Wasm file and produces a Wasm file that has the metadata embedded as a custom Wasm section.
```console
$ kwctl inspect file:///home/flavio/hacking/kubernetes/kubewarden/kwctl/annotated.wasm
Metadata:
---
protocolVersion: v1
rules:
- apiGroups:
- ""
apiVersions:
- v1
resources:
- pods
operations:
- CREATE
- UPDATE
labels:
io.kubewarden.policy.url: "https://github.com/chimera-kube/psp-apparmor"
io.kubewarden.policy.license: Apache-2.0
io.kubewarden.policy.source: …
```

Metadata commands

---

Cargo.lock
Cargo.toml
src/inspect.rs
src/main.rs
src/manifest.rs
src/metadata.rs
src/utils.rs

This PR introduces the new `manifest` command. This command uses the metadata embedded into the policy to generate a [ClusterAdmissionPolicy](https://doc.crds.dev/github.com/kubewarden/kubewarden-controller/policies.kubewarden.io/ClusterAdmissionPolicy/v1alpha1@v0.1.0) resource.
Example of usage:
```console
$ kwctl manifest 'file:///home/flavio/hacking/kubernetes/kubewarden/kwctl/annotated.wasm' --type ClusterAdmissionPolicy`
---
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
name: generated-policy
spec:
module: "file:///home/flavio/hacking/kubernetes/kubewarden/kwctl/annotated.wasm"
settings: {}
rules:
- apiGroups:
- ""
apiVersions:
- v1
resources:
- pod
operations:
- CREATE
- UPDATE
mutating: false
```
**Note well:**
* The output produced by this …

Add `manifest` command

---

Cargo.lock
Cargo.toml
src/main.rs
src/run.rs

Show the tracing events produced by policy-evaluator and other crates we use.
This is extremely useful to debug broken policies.
This PR introduces also a `--verbose` flag that changes the log level of the tracing events.
Note well: this PR is built on top of https://github.com/kubewarden/kwctl/pull/25

Show tracing events

---

Cargo.lock
Cargo.toml
src/main.rs
src/run.rs

Split the `run` code into smaller units. IMHO that improves readability and allows for better handling of the errors (if we want to).
Note well: this is build on top of https://github.com/kubewarden/kwctl/pull/26/

Improve readability

---

Cargo.lock
Cargo.toml
src/main.rs
src/run.rs
src/utils.rs

If `kwctl run` command is called with a module without a scheme,
assume the `file://` scheme, rooted on the local directory. This way,
it's possible to run modules in the following ways:
- `kwctl run registry://ghcr.io/kubewarden/policies/safe-labels:v0.1.2 -s <settings> -r <request>`
- `kwctl run file://$(pwd)/safe-labels.wasm -s <settings> -r <request>`
- `kwctl run safe-labels.wasm -s <settings> -r <request>`

feat: allow to skip scheme on `kwctl run` command

---

Cargo.lock
Cargo.toml
src/inspect.rs
src/main.rs

The `kwctl inspect` command now produces colorized and formatted output.
It's still possible to produce simple YAML outpout by using the `-o yaml` flag.
**Note well:** this branch depends on a currently unreleased version of the `policy-evaluator` crate, see https://github.com/kubewarden/policy-evaluator/pull/7
The next examples take a policy that was annotated using this metadata:
```yaml
rules:
- apiGroups: [""]
apiVersions: ["v1"]
resources: ["pods"]
operations: ["CREATE", "UPDATE"]
mutating: false
labels:
production: false
annotations:
name.castelli.hello: world
io.kubewarden.policy.title: psp-apparmor
io.kubewarden.policy.description: Replacement for the Kubernetes Pod Security Policy that controls the usage of AppArmor profiles
io.kubewarden.policy.author: Flavio Castelli …
```

Introduce "pretty" inspect output

---

.github/workflows/release.yml

* Ensure all the unit tests are green
* Ensure the linux musl binary we're about to release passes the e2e   tests
* Change the name of the zip to include the OS and ARCH

Improve release process

---

Cargo.lock
Cargo.toml
src/annotate.rs
src/constants.rs
src/inspect.rs
src/main.rs

Ensure kwctl writes its version when annotating a policy.
At the same time, ensure `inspect`ion of a policy shows who annotated it.

Handle the annotatedBy field of policy metadata

---

src/main.rs

Previous to this commit, kwctl relied only on the contents of `~/.config/kubewarden/config.json`. The contents of `~/.docker/config.json` were ignored.
This patch gives high priority to kubewarden's configuration file but, when this doesn't exists, attempts to fall back on docker's
configuration file.

Ensure the docker configuration is read as well

---

src/main.rs
src/run.rs

This PR brings back two features that got lost during the `policy-testdrive` -> `kwctl` rewrite. They are both related with the behaviour of the `run` command:
1. Allow user to specify the policy settings on the cli, via the new `--settings-json` flag. This makes the process of writing bat tests easier
2. Ensure the settings provided by the user are actually validated. This must happen **before** the request is evaluated. Invalid settings lead `kwctl` to exit with an error

Policy testdrive missing features

---

Cargo.lock
Cargo.toml
src/annotate.rs
src/main.rs
src/push.rs
src/run.rs

This is a super initial integration. Since we haven't fully discussed the metadata to use to decide the runtime, a commit is added that forces `Opa` for testing manually. However, this needs to change before this PR is merged.
Fixes: https://github.com/kubewarden/policy-evaluator/issues/15

Initial integration for running OPA/OPA Gatekeeper policies

---

Cargo.lock
Cargo.toml
src/annotate.rs
src/backend.rs
src/inspect.rs
src/main.rs

Update the `annotate` and `inspect` commands to handle the new `executionMode` metadata attribute.
This fixes https://github.com/kubewarden/kwctl/issues/57

Handle execution mode inside of annote and inspect

---

src/main.rs
src/push.rs

Refuse to push a rego policy that doesn't have metadata, even when the user gives the `--force` flag.
This is the last item on this list: https://github.com/kubewarden/kwctl/issues/55

Do not push rego policies if they do not have metadata

---

Cargo.lock
Cargo.toml
src/annotate.rs
src/backend.rs
src/cli.rs
src/inspect.rs
src/main.rs
src/push.rs
src/run.rs
src/utils.rs

Finally merge the whole `opa` branch. This allows to handle policies written using Rego

Enable evaluation of Rego-based policies

---

src/cli.rs
src/main.rs
src/verify.rs

Some small fixes and improvements related with logging:
* fix: restore the behaviour of the `-v` flag. It stopped working because of a typo on our side.
* feat: silence the tracing events coming from one of our transient dependencies
* feat: add some debug statements here and there

Small fixes to logging

---

Cargo.lock
Cargo.toml
src/cli.rs
src/main.rs
src/push.rs

Change the `push` command to print the immutable reference to the policy image on the STDOUT.
The `push` sub-command has now a new optional parameter called `--output`. By default the immutable reference will be printed in a "human-friendly" mode, but the user can also print it as JSON, making it possible to parse it with scripts/automation.
The main reason for this change is to allow a more secure Sigstore signature process to our end users.
Signing an image by tag is not secure, because tags are mutable. There could be race conditions or even attacks that could lead the user to sign a different content from what he expected. 
Signing by immutable reference, on the other hand, is not affected by these issues.

enable more secure policy signing

---

Cargo.lock
Cargo.toml
Makefile
e2e-tests/e2e.bats
e2e-tests/test-data/sigstore/verification-config-keyless.yml
e2e-tests/test-data/sigstore/verification-config.yml
src/cli.rs
src/main.rs
src/run.rs
src/verify.rs

Part of https://github.com/kubewarden/policy-server/issues/142
Implement Sigstore keyless verification for`kwctl {verify,pull,run}`.
Now, accept new `--verification-config-path` that contains the config from [the Sigstore verification RFC](https://github.com/kubewarden/kubewarden-controller/blob/main/rfc/0003-policy-signing.md).
Previous flags are still supported: they get translated into a VerificationSettings config, to be used with the verification.
Run `make test e2e-test`.
Added e2e-tests that exercise `--verification-config-path`. 
Depends on https://github.com/kubewarden/policy-fetcher/pull/55.
Create verification-config:
Provide better info on missing signatures: opened https://github.com/kubewarden/policy-fetcher/issues/57
Provide default verification-config: opened …

feat: Keyless verification for kwctl {verify,pull,run} 

---

Cargo.lock
Cargo.toml
e2e-tests/secure_supply_chain_tests.bats
src/cli.rs
src/main.rs
src/run.rs
src/sigstore.rs
src/verify.rs

Leverage the TUF integration offered by sigstore-rs to download Fulcio and Rekor data from the official TUF repository of sigstore.
Users are still allowed to provide custom Fulcio and Rekor data by loading it from the local filesystem.
This fixes https://github.com/kubewarden/kwctl/issues/177
Note well: this builds on top of https://github.com/kubewarden/policy-fetcher/pull/67 - I'll rebase the code once it gets merged

feat: sigstore - download keys and certs from TUF repo

---

Cargo.lock
Cargo.toml
src/pull.rs
src/verify.rs

> **Note well:** this PR depends on https://github.com/kubewarden/policy-fetcher/pull/69 - It's currently in draft mode, but it can be reviewed.
> Once the PR is merged, and a new version of policy-fetcher is tagged, I'll update the PR to consume the freshly tagged version.
Latest policy-fetcher changed some of its public API. This commit fixes the compilation.

Update to latest policy-fetcher

---

Cargo.lock
Cargo.toml
src/run.rs

Add calback handler to evaluator, so we can use test policies that uses sigstore verification
Fix #205

feat: Support kwctl run for sigstore container verification

---

Cargo.lock
Cargo.toml

Update to latest version of policy-evaluator, so that new waPC functions are supported.
This is needed to fix https://github.com/kubewarden/policy-server/issues/236

Support policies performing revers DNS lookups

---

Cargo.lock
Cargo.toml
src/run.rs

Update dependencies to:
* Include the oci-distribution fix for pushing Wasm modules bigger than 4Mb
* Remove the `kube` dependencies, just consume it through `policy-evaluator`

Release 0.3.4

---

Cargo.lock
Cargo.toml
src/cli.rs
src/main.rs
src/run.rs

> **Warning:** this PR depends on https://github.com/kubewarden/policy-evaluator/pull/137
Wasmtime performs a series of operations when a Wasm module is instantiated (see [the official docs](https://docs.wasmtime.dev/contributing-architecture.html?highlight=jit#instantiating-a-module)).
These operations can take a significant amount of time with big WebAssembly modules (like the ones produced by TinyGo when Kubernetes native types are used), which is a big problem for kwctl.
Wasmtime has a feature called "cache", which saves an optimized version of the WebAssembly module to disk, so that it can be later reused to quickly start new instances of it.
The `wasmtime` cli tool is using this feature by default, hence it's considered stable.
This change will make `kwctl` enable the wasmtime cache …

Enable usage of wasmtime cache

---

src/main.rs

The warning messages are not critical, but they confuse the users.
Moreover, they pollute the stdout, leading to end to end test breakage.
Fixes https://github.com/kubewarden/kwctl/issues/240

Suppress wasmtime cache warnings

---

Cargo.lock
Cargo.toml

- deps: Consume policy-evaluator 0.4.4. Adds support for signature verification via github_actions and keyless_prefix.
- build: Bump version to 1.1.0.

Consume policy-evaluator 0.4.4, and bump version to 1.1.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
e2e-tests/secure_supply_chain_tests.bats
src/main.rs
src/run.rs
src/verify.rs

Allow Fulcio and Rekor data to be None. This means we will be missing
info from the transparency log, therefore not being able to validate
correct signatures, and giving false negatives.
Warn about it, and continue.
This protects us when upstream's Sigstore TUF repository has problems.
```
$ ./kwctl verify --verification-config-path=./../../e2e-tests/test-data/sigstore/verification-config-keyless.yml registry://ghcr.io/kubewarden/policies/capabilities-psp:v0.1.9
2022-07-19T09:57:04.387681Z  WARN kwctl: Cannot fetch TUF repository: TufError(ParseMetadata { role: Targets, source: Error("missing field `length`", line: 24, column: 4), backtrace: Backtrace(()) })
2022-07-19T09:57:04.387762Z  WARN policy_fetcher::verify: Sigstore Verifier created without Fulcio data: keyless signatures are …
```

fix: Warn and continue when Sigstore TUF repository is broken

---

e2e-tests/secure_supply_chain_tests.bats

This reverts commit 5b1d93565200f2f21a1c3dd87197430fcd914c22.
Once the release was done, and the upstream TUF repository metadata is correct again,
we can re-enable this test.
e2e-tests via GHA.

fix: Reenable TUF integration test

---

Cargo.lock
Cargo.toml
src/annotate.rs
src/cli.rs
src/main.rs
src/scaffold.rs

The mdbook dependency caused an upgrade of the clap one in an indirect fashion. That lead me to be explicit about the version fo clap to be used.
The clap update requried several fixes because of some deprecation warnings. Everything is working fine according to the e2e tests.
Supersedes PR https://github.com/kubewarden/kwctl/pull/274
**UPDATE**
I've also updated the `validator` crate, which could not be handled via dependabot. This one requires https://github.com/kubewarden/policy-evaluator/pull/166 to merged and a new version of `policy-evaluator` to be tagged.
Once this is done I'll update the `Cargo.toml` accordingly.
Now this PR supersedes also https://github.com/kubewarden/kwctl/pull/270

Upgrade dependencies

---

.github/workflows/release.yml

This PR involves just a CI Job to be executed on release time.
```shell
rustup target add aarch64-apple-darwin
cargo build --target=aarch64-apple-darwin --release
```
I already validated that it works on a M1 processor
Signed-off-by: Juan Manuel Parrilla Madrid <jparrill@redhat.com>

ci: Added CI Job to release Apple Silicon binary with the release GH Actions flow

---

Cargo.lock
Cargo.toml
src/main.rs

We don't need the rest of the features as our use of syntect is minimal:
`syntect::parsing::SyntaxSet::load_defaults_newlines()` for mdcat.
This reduces deps and compilation time, plus removes the dependency on
`plist`, which on its own depends on `xml-rs`.
`xml-rs` is unmaintained, a RUSTSEC advisory has been issued for it:
https://rustsec.org/advisories/RUSTSEC-2022-0048.html
Fix https://github.com/kubewarden/kwctl/issues/282
Tested with `make e2e-tests`, and checking that `kwctl inspect` (the codepath hit) keeps working as intended.

deps: Set syntect to only use `parsing` feature

---

.cargo/config
.github/workflows/release.yml

After a DDoS attack the maintainer of the musl.cc domains blocked the
request caming from some cloud providers. This prevent us from
downloading the tarball needed to cross-compile the policy-server.
Therefore, the workflow has been updated to use the musl package
available in the Ubuntu 22.04 packages.
Fix #281

 Use Musl from Ubuntu packages.

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Revert PR about making `v1.2.0`, we will go with `v1.1.3`, as `v1.1.2` was tagged already yet unreleased because of the musl cross-compiling issues.

Road to 1.1.3

---

.github/workflows/release.yml
Makefile

Instead of download the SBOM generation tool in the workflow use the github action used in other repositories.
Depends on https://github.com/kubewarden/github-actions/pull/39

Use github action to install SBOM generation tool.

---

Cargo.lock
Cargo.toml
src/annotate.rs
src/inspect.rs
src/scaffold.rs

Depends on https://github.com/kubewarden/policy-evaluator/pull/197
Fix https://github.com/kubewarden/kwctl/issues/330
Fix https://github.com/kubewarden/kwctl/issues/331
`kwctl annotate` will default it to `true` if not provided.
`kwctl scaffold` will default it to `true` if not provided.
`kwctl inspect` shows it, defaulting to `true` if not present.
Tested in policy-evaluator.
Backwards compatibility is working; the e2e tests pass, without needing to re-annotate the policies with `backgroundAudit`.

 feat: Support metadata.backgroundAudit 

---

.github/workflows/fossa.yml
.github/workflows/release.yml
.github/workflows/security-audit-cron.yml
.github/workflows/security-audit-reactive.yml
.github/workflows/tests.yml

Setting token permissions to read-only follows the principle of least privilege. This is important because attackers may use a compromised token with write access to push malicious code into the project. [More info](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions)
This will increase our CLOMonitor score
Fix https://github.com/kubewarden/kwctl/issues/341

Add read-all permission to all workflows

---

.github/workflows/release.yml

Build image gh action was broken when we introduced permissions: read-all at the top level of all files. 
This PR sets the permissions at job level instead, which fixes the issue. This should also be ok with CLOMonitor. We won't get the maximun score for the token permission (10) but it should give us more than 4 that is required for the check to be green. [More info](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions)
Everything worked fine when I created a release in my fork with [this changes](https://github.com/raulcabello/kwctl/actions/runs/3384521485)

Add permission at the job level

---

.clomonitor.yml

Add CLOMonitor exemption for `artifacthub_bagde`, `kwctl` is a cli binary and can't be published there.
See https://clomonitor.io/docs/topics/checks/#exemptions

chore: Add CLOMonitor exemption for `artifacthub_badge`

---

Cargo.lock
Cargo.toml
e2e-tests/e2e.bats
src/cli.rs
src/load.rs
src/main.rs
src/save.rs

There are two new commands in this PR:
- `save`: stores the provided policies into a tarball
- `load`: load the policies in the tarball into the default store
This is needed for airgap support. Policies will be stored into a tarball, then this tarball is moved to the airgapped environment. Finally, `kwctl load` is used to import the policies in the airgapped environment.
Fix #346

save and load commands

---

.github/workflows/release.yml

Scripts can be found in this [release](https://github.com/raulcabello/kwctl/releases/tag/v0.1.3.7)
Fix #363

add airgap scripts to releases

---

Cargo.lock
Cargo.toml

Update to latest version of policy-evaluator to support the new certificate based verification host capability.
Fixes https://github.com/kubewarden/kwctl/issues/350

feat: support certificate based verification

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Release `1.4.0-rc1`.
This is a minor Kubewarden version (policy-server, charts, etc will follow). This version supports verifying Sigstore signatures done using x509 certificates and their certificate chains.
Tested by manually using this unreleased `kwctl 1.4.0-rc1` to run the e2e tests of verify-image-signatures-policy.
To be tagged  `1.4.0-rc1` once it lands in main.

Release 1.4.0-rc1

---

Cargo.toml
src/cli.rs
src/main.rs

The bench command should not attempt to write the benchmarks results to disk by default.
The crate we're using has a hard-coded path which exists only when inside of a Rust project.
Prior to this commit, the following warning messages (shown in red) were printed when the path was not found:
```console
Failed to read last sample, cause Could not find target directory to place output
Failed to write sampling data, cause: Could not find target directory to place output
```
This can mislead/scare end users.
This commit disables this behavior and introduces a new flag that can be used to write the results back to disk.

bench do not write results to disk by default

---

Cargo.lock
Cargo.toml
src/backend.rs
src/bench.rs
src/run.rs

Update to latest stable release and fix breakage caused by the API.

chore: update to latest policy-evaluator

---

Cargo.lock
Cargo.toml

Changes:
- build(deps): bump wasmparser from 0.95.0 to 0.96.0 (#384)
- fix: use system certificates (#386)
- chore: update to latest policy-evaluator (#385)
- chore: update rust edition (#382)
- chore(deps): lock file maintenance (#381)
- build(deps): bump tokio from 1.22.0 to 1.23.0 (#380)
Signed-off-by: Flavio Castelli <fcastelli@suse.com>

Release v1.4.2

---

.github/workflows/release-drafter.yml

Updates the CI release drafter job to be triggered when the a PR is edited. With that the autolabeler will run when the PR title is changed.

Run autolabeler when a PR is edited

---

.github/workflows/release.yml

Updates the release kwctl CI job to trigger an event to the Helm chart repository to ensure that the major and minor releases will be in sync between all Kubewarden components.
Fix #366

Trigger Helm chart release.

---

.github/release-drafter.yml

Updates the release drafter configuration file changing the label used to exclude a PR from the change log to `release/skip-changelog`.
Adds a new entry in the autolabel configuration to set the label `area/dependencies` when the PR title starts with `build(deps)`

 Fix release drafter autolabeler and exclude-labels.

---

Cargo.lock
Cargo.toml

In a recent update of mdcat the crate use `native-tls` with its `reqwest` dependency configuration. This cause an issue in our build because our cross-compilation environment does not have OpenSSL.
To fix the issue, the mdcat is now configured to use rustls. Therefore, the OpenSSL dependency is not needed.

Configure mdcat to use rustls.

---

Cargo.lock
Cargo.toml

We forgot to bump the version attribute inside of `Cargo.toml`.
This fixes https://github.com/kubewarden/kwctl/issues/409

fix: report the right version

---

Cargo.lock
src/scaffold.rs

Currently the `backgroundAudit` field is not known by the Kubewarden's stable CRDs.
Because of that, we should not generate this attribute at scaffold time.
This is a quick workaround for https://github.com/kubewarden/kubewarden-controller/issues/395
Note: the field is not scaffolded when it's `true`, which is the default case. A policy with `backgroundAudit` set to `false` would still cause the scaffold code to produce this field, leading to this bug again. However this is not a big deal, since no policy is currently setting this attribute. On the other hand, we need kwctl to generate this attribute for our development purposes.

fix: scaffold should not generate the backgroundAudit field

---

.github/workflows/build.yml
.github/workflows/tests.yml

Cosign 2.0 was [released last week](https://blog.sigstore.dev/cosign-2-0-released/) (yay!) but, as expected because semver, it's not backwards compatible (nay!).
Pin cosign-installer GHA so it downloads cosign 1.*.
Latest [cosign-installer downloads cosign 2.*](https://github.com/sigstore/cosign-installer/releases/tag/v3.0.0).
Tested in my fork:
https://github.com/viccuad/kwctl/actions/runs/4315689467/jobs/7530608694 (that commit tag only had the linux build fixed there).

deps: Pin cosign to 1.* by pinning cosign-installer GHA

---

Cargo.lock
Cargo.toml
src/annotate.rs
src/cli.rs
src/main.rs
src/scaffold.rs

Fix https://github.com/kubewarden/kwctl/issues/418
Depends on https://github.com/kubewarden/policy-evaluator/pull/246 
feat: Add `kwctl scaffold artifacthub` command 
feat: Add `--usage` flag to `kwctl annotate`
Depend on `time` crate.
Example:
```
kwctl scaffold artifacthub \
--metadata-path metadata.yml \
--version 0.2.1 \
--questions-path questions-ui.yml > artifacthub-pkg.yml
```
Relevant `annotate` unit test has been added, artifacthub functionality is tested in policy-evaluator, and e2e tests are unnecessary.
Right now `--version` is mandatory.

feat: Add `kwctl scaffold artifacthub` command, add `kwctl annotate --usage` flag

---

Cargo.lock
Cargo.toml

- build: Consume policy-evaluator 0.8.0, to serialize artifacthub-pkg.yml deterministically
- build: Bump version to 1.6.0-rc2
- build: Update cargo.lock

fix: Serialize artifacthub-pkg.yml deterministically, bump to 1.6.0-rc2

---

Cargo.lock
src/callback_handler/mod.rs
src/callback_handler/proxy.rs
src/cli.rs
src/main.rs
src/run.rs

Allow user to record all the policy <-> host interactions done via the host capabilities feature.
All the exchanges are written to a yml file that can then be played back via a new cli flag.
This allows e2e test to run in fully reproducible way, without requiring any external service like DNS, oci registries and Kubernetes,...
This PR depends on:
* https://github.com/kubewarden/policy-sdk-rust/pull/83
* https://github.com/kubewarden/policy-evaluator/pull/261
Expect the test suite to fail until these PRs are merged and the `Cargo.lock` file is updated

feat: introduce record/replay of host capabilities

---

.cargo/audit.toml

cargo-audit is complaining because the `mach` dependency is currently not maintained.
This is a transitive dependency of wasmtime.
The issue is tracked upstream via https://github.com/bytecodealliance/wasmtime/issues/6000
In the meantime we will silence this warning.

chore: fix cargo audit

---

Cargo.lock
Cargo.toml
src/run.rs

When the host-capabilities replay mode is enabled, do not attempt to connect to Kubernetes.
This is needed to allow `kwctl run` to be used inside of environments where Kubernetes does not exist, such as running e2e tests inside of GitHub actions

fix: allow execution of e2e tests when k8s is not available

---

src/cli.rs
src/main.rs

Adds a new command line argument for the `scaffold artifacthub` subcommand to allow users to define where the artifacthub file content will be written. The new flag is optional. When not defined the content of the file will be written in the stdout.

feat: --output flag to scaffold artifacthub command.

---

Cargo.toml
src/main.rs

By updating to latest version, `info` messages are now shown to our users.
Because of that, we can address some `TODO` items we had left.

chore(deps): update mdcat to latest version

---

src/info.rs

The `info` command was printing a `"` symbol.
While working on that, I've also made the command print the path of the directory where the default configuration is stored.

fix: address small leftover

---

src/main.rs

Walrus prints an innocent warning message while annotating a policy.
This can cause users to be confused.
This commit suppresses all the warning messages produced by walrus, but leaves the error ones untouched.
Fixes https://github.com/kubewarden/kwctl/issues/461

fix: hide walrus warning message

---

Cargo.lock
Cargo.toml
src/backend.rs
src/inspect.rs
src/run.rs

Updates the kwctl run and bench commands to check if program version is compatible with the minimum Kubewarden version required by the policy.
It also add a new field in the inspect command to show the minimum Kubewarden version required to run the policy.
Fix #467 
```shell
$ kwctl inspect registry://ghcr.io/jvanz/policies/allow-privilege-escalation-psp:latest | grep minimum
2023-04-11T18:36:39.193625Z  INFO sigstore::cosign::client_builder: Rekor public key not provided. Rekor integration disabled
2023-04-11T18:36:39.193689Z  INFO sigstore::cosign::client_builder: No Fulcio cert has been provided. Fulcio integration disabled
minimum kubewarden version: 1.7.0 
$ kwctl run registry://ghcr.io/jvanz/policies/allow-privilege-escalation-psp:latest --request-path …
```

Check minimum Kubewarden version.

---

Cargo.lock
Cargo.toml
src/inspect.rs

The mdcat maintainer moved all the rendering code into a dedicated crate. This allows use to use a more idiomatic approach to the consumption of this dependency.

chore(deps): remove mdcat dependency

---

e2e-tests/e2e.bats
src/cli.rs
src/inspect.rs
src/main.rs

The `--no-color` flag removes color from the output. It also disables color from the logs genearted by `tracing` crate.
Fixes #195 
I am modifying the `TERM` env variable to disable color. This is referenced from [here](https://docs.rs/termcolor/1.2.0/src/termcolor/lib.rs.html#255). The changes made to the TERM variable using `env::set_var("TERM", ...)` are specific to the current process and its child processes. Once the process terminates, the environment variable will revert to its previous value.

(feat) added feature to disable colorful output with --no-color flag

---

Cargo.lock
Cargo.toml
src/inspect.rs

Use latest version of policy-evaluator in order to consume the latest version of sigstore

chore(deps): update policy-evaluator

---

Cargo.lock
Cargo.toml
src/annotate.rs
src/backend.rs
src/cli.rs
src/run.rs

Support policies that implement the new WASI protocol.
This policy execution mode is not the best one, but it allows the execution of WASM modules that do not leverage waPC. This is the case of modules built by the official Go compiler.

feat: support WASI policy

---

Cargo.lock
Cargo.toml

Updates the Cargo.toml and Cargo.lock file bumping the version to v1.7.0-rc1.
Related to https://github.com/kubewarden/kubewarden-controller/issues/473

Bump v1.7.0-rc1 version.

---

.github/release-drafter.yml

Updates the release CI to publish the draft release created by release drafter instead of creating a new release. Therefore, we will use the nice changelog.

fix: publish release drafter draft release.

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/tests.yml

Updates the CI scripts updating the cosign-installer to v3. Thus, the cosign version now is v2. Which has breaking changes requiring some changes on how the command is called and removing the need of using environment variable to enable keyless signature.
Also updates the sbom-generator-installer action to version v2.
Related to https://github.com/kubewarden/kubewarden-controller/issues/411

Updates cosign and sbom-generator-installer to v2.

---

Cargo.lock
Cargo.toml
src/scaffold.rs

Fix https://github.com/kubewarden/kwctl/issues/529
Depends on https://github.com/kubewarden/policy-evaluator/pull/302
Unit tests.
Performed a manual e2e test, yet I don't think it is necessary to add a specific e2e test for this.
Add an enum for severity (`info`, `low`, `medium`, `high`) in policy-evaluator, to be consumed by kwctl here.
This would allow for `kwctl annotate` to error if the severity annotation in metadata.yaml doesn't conform to those values. Hence, a policy author would realize that they are creating an incorrect default for the severity.
But, since the severity can be changed after doing a `kwctl scaffold`, and we expect cluster admins to set their own severity, I don't see much value in doing this leg work. I could be convinced though!
If the severity would be part of …

feat: `kwctl scaffold` prints severity and category annotations when they are in policy metadata

---

.github/workflows/release.yml

Updates the release CI to check if the pushed tag has some text indicating a release candidate and set properly the flag to publish the release as final release or a candidate.
Related to https://github.com/kubewarden/policy-server/pull/497/files#r1268541197

fix: enable release candidates when required.

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/fossa.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml
.github/workflows/security-audit-cron.yml
.github/workflows/security-audit-reactive.yml
src/backend.rs
src/run.rs

The GH action uploading the release assets must provide the base name of the file, not its full path.
With kubewarden 1.7.0-rc2 we accidentally got all the release assets to contain the entire path to the file. For example, we had `default.kwctl-airgap-scripts.kubewarden-load-policies.sh` instead of
`kubewarden-load-policies.sh`.

fix: Ensure release assets have proper name

---

Cargo.lock
Cargo.toml
e2e-tests/e2e.bats
src/cli.rs
src/inspect.rs
src/main.rs
src/rm.rs
src/run.rs
src/save.rs
src/scaffold.rs
src/utils.rs

This PR adds the support for referring to a policy in the store using a sha value to the following commands:
- run
- inspect
- scaffold manifest
- bench
- push
- rm
- save
Closes: #97 
This feature emulates the docker cli, by accepting a partial sha or a URI.
Since we deal with relative paths, the sha path is used only if a file with the same name does not exist (aka files have precedence). 
If by using a sha prefix multiple policies are found, an error is returned.
E.g.:
```
$ kwctl policies
+--------------------------------------------------------------+----------+---------------+--------------+-----------+
| Policy                                                       | Mutating | Context aware | SHA-256      | Size      |
+--------------------------------------------------------------+ …
```

feat: support sha prefix as argument

---

Cargo.lock
Cargo.toml

Updates the Cargo.toml file bumping the version to v1.7.0-rc3.
Related to https://github.com/kubewarden/kubewarden-controller/issues/519

Bump v1.7.0-rc3 version.

---

.github/workflows/release.yml

The release CI script is missing a step to trigger the helm update. This is necessary to sync the release among all the major Kubewarden components.
Related to https://github.com/kubewarden/kubewarden-controller/issues/519

fix: missing step to trigger helm chart update.

---

Cargo.lock
Cargo.toml
src/bench.rs
src/cli.rs
src/main.rs
src/run.rs
src/scaffold.rs
tests/data/context-aware-policy-request-pod-creation-all-labels.json
tests/data/raw.json
tests/e2e.rs
tests/secure_supply_chain_e2e.rs

Adds a `--raw` flag to run and bench.
The `--raw` flag specifies that the policy will be evaluated as a raw policy. 
Updates existing tests.
Adds --raw flag e2e test and fixes.
Updates `tests/data/context-aware-policy-request-pod-creation-all-labels.json` fixture since now we try to unmarshal requests to types and the fixture had missing fields.
-

feat: add --raw flag to run and bench

---

Cargo.lock
Cargo.toml
src/inspect.rs
src/run.rs
tests/e2e.rs

- show policyType when inspecting a policy
- run a policy in raw "mode" if the policyType metadata is set to raw, otherwise the user needs to pass a `--raw` flag (which takes precedence over the metadata, in case the policy is not annotated)
Adds e2e tests
Bumps Cargo toml to `v1.9.0-rc1`

feat: use policyType metadata

---

src/run.rs

Due to recent changes, the AdmissionRequest validation is stricter. Some of our e2e test fixtures are missing required values, making the test fail (which is the right thing to do).
This commit improves the error message given when the AdmissionRequest object is failing the validation. This makes everything less cryptic.
Prior to this commit:
```console
kwctl run \
-r test_data/ns_without_labels.json \
--allow-context-aware \
--replay-host-capabilities-interactions test_data/session_project_found.yml \
annotated-policy.wasm
Error: missing field `group`
```
With this commit:
```console
kwctl run \
-r test_data/ns_without_labels.json \
--allow-context-aware \
--replay-host-capabilities-interactions test_data/session_project_found.yml \
annotated-policy.wasm
Error: cannot build …
```

fix: improve error message when AdmissionRequest is not valid

---

Cargo.lock
Cargo.toml
src/run.rs
src/scaffold.rs

Ensure the rego inventory of Kubernetes resources is built in a deterministic way. Without that, a `kwctl run` outcome might fail without a valid reason.
This issue was reported by @brunorene
This depends on https://github.com/kubewarden/policy-evaluator/pull/389

fix: Make Rego inventories ordered and deterministic

---

Cargo.lock
Cargo.toml

- fix: Make Rego inventories ordered and deterministic (#655)
- Update many deps

Tag 1.9.1 release

---

src/cli.rs
src/inspect.rs
src/main.rs
tests/e2e.rs

- fix: do not break yaml output of `inspect` (fixes https://github.com/kubewarden/kwctl/issues/659)
- feat: by default do not show signagures inside of inspect output

Improve inspect cmd

---

Cargo.lock
Cargo.toml

kube 0.88.0 introduced a minor regression: https://github.com/kube-rs/kube/pull/1398
That caused kwctl 1.10.0 to fail while running e2e tests under specific circumstances. Replaying a host capabilities sessions recorded with an older version of kwctl would cause Rego policies to fail. waPC policies would not fail.
This patch release of kwctl addresses this specific regression.
**Note well:** once this PR is merged I'll tag a new patch release of kwctl (v1.10.1)
Fixes https://github.com/kubewarden/kwctl/issues/701

fix: Consume latest version of kube

---

.github/workflows/ci.yml
.gitignore
Makefile
coverage/integration-tests/.gitignore
coverage/unit-tests/.gitignore

Fix https://github.com/kubewarden/kwctl/issues/722
CI.
We should get the codecov message.

ci: Add codecov support

---

Cargo.lock
Cargo.toml

This changes how kubernetes resources are fetched by policies. This is not a big change for kwctl, since it's a short lived process

chore(deps): update to latest policy evaluator

---

.cargo/audit.toml

Ignoring `RUSTSEC-2023-0081`, which is about `safemem` being unmaintained. This is a transitive dependency of syntect. This bug is tracked upstream inside of https://github.com/trishume/syntect/issues/521

Address cargo audit warning

---

Cargo.lock
Cargo.toml

Updates the version in the Cargo.toml file to v1.11.0-rc3.

chore: bumps version in Cargo.toml to v1.11.0-rc3.

---

.github/workflows/ci.yml

Updates the ci.yaml workflow file to use the new github action created to install the cargo tarpaulin.
Fix #https://github.com/kubewarden/kubewarden-controller/issues/667

chore: use tarpaulin-install action to install tarpaulin.

---

.github/workflows/ci.yml

`cargo install --path .` ignores Cargo.lock
We need to add the `--locked` flag.
See: https://github.com/rust-lang/cargo/issues/6983

fix(ci): cargo install ignores lockfile if --locked is not passed

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
src/callback_handler/mod.rs
src/callback_handler/proxy.rs
src/cli.rs
src/main.rs
src/run.rs
src/verify.rs
tests/secure_supply_chain_e2e.rs

The Sigstore project changed the internals of its TUF repository, which broke sigstore-rs.
This commit updates to the latest version of sigstore-rs. The code changes have been caused by the massive changes done by sigstore-rs.
Fixes https://github.com/kubewarden/kwctl/issues/753

fix: address changes done to Sigstore TUF repository

---

.github/workflows/security-audit-cron.yml
.github/workflows/security-audit-reactive.yml

Move to the official GH action provided by the cargo-audit team. The old one seems abandoned.

chore(deps): change GH action used by cargo-audit

---

Cargo.lock
Cargo.toml
src/cli.rs
src/main.rs
src/scaffold.rs
tests/data/vap/vap-binding.yml
tests/data/vap/vap-with-variables.yml
tests/data/vap/vap-without-variables.yml
tests/e2e.rs

Add the new `scaffold vap` subcommand. This allows to create a Kubewarden ClusterAdmissionPolicy starting from a Kubernetes ValidatingAdmissionPolicy.

feat: scaffold KW policy from Kubernetes ValidatingAdmissionPolicy

---

src/main.rs
src/run.rs

When the policy settings validation failed, the error message printed twice in the console. This commit fix that by removing a where the error is printed once.
It's not possible to improve more the error message because the JSON shown in some error came from a string with the error message returned by the settings validator. It's not possible to kwctl to easily improve that without string manipulations.
Fix #801 
This is an example of an error message with this change:
```console
$ ./target/release/kwctl run --request-path pod_creation_signed.json --settings-path ./settings2.json registry://ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.8             ✔ │ 9s │ 15:35:12 
Error: Error running policy registry://ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.8: Provided …
```

fix: improve error handling in settings validation.

---

Cargo.lock
Cargo.toml

Bumps the kwctl version in the Cargo files to v1.14.0-rc1.

chore: bump version to v1.14.0-rc1

---

Cargo.lock
Cargo.toml

Bumps the kwctl version in the Cargo files to v1.14.0-rc2

chore: bump version to v1.14.0-rc2

---

Cargo.lock
Cargo.toml

Bumps the kwctl version in the Cargo files to v1.14.0

chore: bump version to v1.14.0

---

Cargo.lock
Cargo.toml

Bumps the version in the Cargo files to v1.15.0-rc1

chore: bumps v1.15.0-rc1.

---

Cargo.lock
Cargo.toml
src/cli.rs
src/main.rs
src/scaffold/manifest.rs
src/utils.rs
tests/e2e.rs

Updates the manifest command to pull the policy if it is not in the local storage.
Fix #844

feat: allow `manifest` to pull a remote policy

---

Cargo.lock
Cargo.toml
README.md
src/cli.rs
src/info.rs
src/main.rs
src/scaffold.rs
src/scaffold/admission_request.rs

This command creates a Kubernetes AdmissionRequest object starting from a Kubernetes Resource definition.
The following command:
```console
kwctl scaffold \
admission-request \
--operation CREATE \
--object ingress.yaml
```
produces an AdmissionRequest CREATE event for the given Ingress object.
Currently, only the CREATE operation is supported. The other operations will be added in the future.

feat: introduce scaffold admission-request command

---

Cargo.lock
Cargo.toml
src/inspect.rs
src/scaffold/vap.rs
src/utils.rs

The `oci-distribution` crate has been renamed to `oci-client`

chore(deps): bump policy-evaluator

---

Cargo.lock
Cargo.toml

Fix breaking change done by Sigstore's TUF repository

Prepare 1.16.1 release

---

.cargo/audit.toml

A bunch of warnings have popped up. There's nothing we can do about them and they basically no impact on us.
- "RUSTSEC-2024-0370": This is a warning about `proc-macro-errors` being unmaintained. It's a transitive dependency of `sigstore` and `oci-spec`.
- "RUSTSEC-2023-0055": This is a warning about `lexical` having multiple soundness issues. It's a transitive dependency of `sigstore`.

chore: update cargo audit ignore list

---

.github/workflows/ci.yml

This reverts commit bbe9ae3dfb48f4aab75b1936f58cb2589a26cca0. As far as I can see we disable it during the issues with sigstore. Now, we can re enabled it! ;)
Fix #852

Revert "ci: don't generate coverage for e2e tests"

---

.github/workflows/build.yml
.github/workflows/release.yml
README.md

Fix https://github.com/kubewarden/kwctl/issues/933
Provide provenance for `kwctl` cli utility via GitHub provenance attestation GHA. The intent is to provide a simple approach to provenance. Provenance files will be accesible via https://github.com/kubewarden/kwctl/attestations, as well as shipped in the resulting GH Release, since they are signed via Sigstore.
No care has been taken in refactoring prior SBOMs and their signatures into a checksum file, as each of them are run on their own job from the workflow matrix for now.
Tested by running it from my fork, with a drop commit to be able to create a tagged release.
See:
https://github.com/viccuad/kwctl/actions/runs/11407858585 (the error is only in triggering the bot PR)
https://github.com/viccuad/kwctl/releases/tag/v1.18.0-viccuad …

Ensure SLSA Lvl 3

---

Makefile

This is in hopes of reducing tarpaulin time below 15 mins,
so it fits in GHA timeout.
Right now it times out after 15 mins:
https://github.com/kubewarden/kwctl/actions/runs/11442780601
Relates to https://github.com/kubewarden/kwctl/issues/852.
Tested locally, but cannot know about GHA timeout.

ci: Increase timeout for coverage job

---

Makefile

Remove `--force-exec` and allow multi-thread execution when running tarpaulin. 
Fixes #952

fix: remove tarpaulin e2e test --force-exec flag

---

.github/workflows/ci.yml
Makefile

Tarpaulin has a memory leak, continue on error for coverage job so releases can go forward.
See: https://github.com/xd009642/tarpaulin/issues/1639

ci: Continue on error for coverage job

---

.github/workflows/ci.yml
Makefile

Switch to cargo-llvm-cov to collect code coverage results. This is required because tarpaulin is consuming too much memory, leading to our GHA being killed.
See https://github.com/xd009642/tarpaulin/issues/1639 for more details.

automation: switch to cargo-llvm-cov

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
Makefile
README.md
cli-docs.md
src/cli.rs
src/main.rs

Adds a new kwctl subcommand to allow users to generate a markdown documentation with all the commands available in kwctl.
Part of #851 
```shell
make && ./target/release/kwctl docs --output cli-docs.md
```

feat(cli): generate markdown documentation.

---

Cargo.lock
Cargo.toml
src/main.rs
src/verify.rs

Upgrade to latest version of sigstore by consuming latest stable release of policy-evaluator.

chore(deps): update sigstore

---

.taplo.toml
Cargo.lock
Cargo.toml
cli-docs.md
src/cli.rs
src/push.rs
src/scaffold/manifest.rs
tests/e2e.rs

When pushing a policy to an OCI registry, add all the Kubewarden annotations found inside of policy's metadata to the resulting OCI manifest.
The KW annotations that are multi-line will be skipped, since they are not compliant with the OCI spec.
Moreover, the `io.kubewarden.policy.source` is propaged as `org.opencontainers.image.source` to allow tools like renovatebot to handle policy updates.
Fixes https://github.com/kubewarden/kwctl/issues/1044
Finally, I've added a `taplo.toml` configuration to the project to keep our `Cargo.toml` file nice and tidy.

feat: OCI annotations

---

.github/workflows/ci.yml

This is needed because of taplo formatting.
Fixes release job.
Tested locally.

ci: Adapt cargo `version-check` job for formatted Cargo.toml

---

Cargo.lock
Cargo.toml
cli-docs.md
src/cli.rs
src/main.rs
src/scaffold/artifacthub.rs

This PR introduces a GitHub release tag to override the version in URL links. See [[kubewarden/policy-evaluator#644](https://github.com/kubewarden/policy-evaluator/pull/644)](https://github.com/kubewarden/policy-evaluator/pull/644).

feat: add gh release to artifacthub scaffold

---

Cargo.lock
Cargo.toml
src/pull.rs

Add a progress bar to the policy pull operation to provide visual feedback during fetching. This enhancement integrates the indicatif crate to display a spinner-style progress indicator that shows when a policy is being pulled, updates with status messages during the operation, and concludes with appropriate success or failure notifications upon completion, improving the user experience without altering the existing functionality.
Fixes #2
`Spinner `
// @flavio

feat: add spinner while pulling resources

---

Cargo.lock
Cargo.toml
src/inspect.rs

Drop `pulldown-cmark`,`pulldown-cmark-mdcat`,`syntect` since `pulldown-cmark-mdcat` is now unmaintained.
Use `termimad` instead.
Before, `kwctl inspect` had syntax coloring for code blocks such as "rules" and those inside the "description".
Now, code blocks don't have syntax coloring.
There's minor variations on printing the "description" markdown. Markdown URL links are flat rendered by `termimad`.
Maintained the feature of disabling color when piping to non-interactive terminal by depending on `is-terminal` (`is-terminal` is already a dependency of `termimad`, yet `termimad` doesn't provide this functionality on its own).
Locally.
Now:
Before:
Now we print code blocks without syntax coloring.
Alternatives:
Fork `pulldown-cmark-mdcat`. To me, `pulldown-cmark`, being a pull parser, …

refactor!: Change `kwctl inspect` colored output

---

cli-docs.md
src/cli.rs
src/main.rs
src/utils.rs
tests/data/artifacthub/metadata.yml
tests/e2e.rs

Let the `scaffold artifacthub` run also without having the user provide the path to the `metadata.yml` and to the questions file.
The user can still provide these values as flags, but when they are not provided we will search for them using standard locations.
This is required as part of https://github.com/kubewarden/kubewarden-controller/issues/956

feat: scaffold artifacthub runs without params

---

cli-docs.md
src/cli.rs

exchange the quotations with a normal single quotations .
Fix #1151

fix(cli): correct quotation marks with normal qutations.

---

.github/workflows/build.yml
.github/workflows/ci.yml

This PR introduces two changes.
Address the build failure currently happening on windows (fixes https://github.com/kubewarden/kwctl/issues/1162).
The GitHub runners based on Windows are now using latest version of CMake (v4).
The aws-lc-sys crate builds itself using cmake, but contains a directive that has been removed from v4.
To fix the build issue, an environment variable has to be set.
Run `cargo check` against windows, linux and macos. This allows us to spot issues earlier, during a PR.
Otherwise the OS-related failures are going to be visible only after PRs are merged and the `build` workflow is triggered.

fix(ci): build on windows

---

Cargo.lock

Update Cargo.lock to address RUSTSEC-2025-002
Fixes https://github.com/kubewarden/kwctl/issues/1170

chore(deps): fix RUSTSEC-2025-002

---

.github/workflows/release.yml

Part of https://github.com/kubewarden/kubewarden-controller/issues/1099.
Tagged a `v1.24.0-viccuad` from my fork, which run:
https://github.com/viccuad/kwctl/actions/runs/14729543239

ci: Substitute peter-evans/repository-dispatch with gh cli

---

.github/workflows/build.yml
.github/workflows/ci.yml

Removes the deprecated actions-rs/cargo Github action used to run cargo commands.
Related to https://github.com/kubewarden/kubewarden-controller/issues/1092

fix(deps): remove deprecated actions-rs/cargo Github action.

---

.github/workflows/build.yml
.github/workflows/update-rust-toolchain.yaml
rust-toolchain.toml
updatecli/DEVELOP.md
updatecli/updatecli.d/update-rust-toolchain.yaml
updatecli/values.yaml

Adds the rust-toolchain.toml file to configure the build command on witch toolchain and target it should use.
Related to https://github.com/kubewarden/kubewarden-controller/issues/1093

chore(deps): add rust-toolchain.toml

---

.github/workflows/ci.yml

Removes some references to the actions-rs/toolchain Github Action in the ci.yml file. This GHA is deprecated and we are rust-toolchain.toml file to configure the toolchain.
Related to https://github.com/kubewarden/kubewarden-controller/issues/1093

chore(deps): removes some actions-rs/toolchain references.

---

Cargo.lock
Cargo.toml

Updates the policy-evaluator version in use in kwctl to allow the run commands to execute policies calling the `kubernetes/can-i` host capability added in v0.27.0.
Fix #1244

feat(capabilities): update policy-evaluator to v0.27.0.

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml

Updates Cargo.toml file to bump kwctl to 1.27.0-alpha2 version

chore: 1.27.0-alpha2 bump.

---

.cargo/audit.toml

Do no longer ignore the `RUSTSEC-2023-0081` issue. The transitive dependency has been updated.

chore: update cargo-audit exceptions

---

Cargo.lock
Cargo.toml

Updates the policy-evaluator to allow kwctl to record and replay crypto host capabilities.

chore: bump policy-evaluator version.
