kubewarden/kwctl

Cargo.lock
Cargo.toml
src/main.rs
src/pull.rs
src/push.rs

Fixes https://github.com/kubewarden/kwctl/issues/3

feat: Implement policy pushing to OCI registries

---

src/main.rs
src/run.rs

Provide more insights about where the error is coming

Improve the error messages of the `run` command

---

src/main.rs

Ensure policy authors push policies that are annotated.
The `push` command however has a `--force` flag that allows users to push a policy that is not annotated.
Fixes https://github.com/kubewarden/kwctl/issues/34

Check whether a policy is annotated before pushing it

---

src/main.rs

Change the push command to take two positional parameters:
1. The policy to be pushed (source)
2. The registry destination (destination)
This allows to push not only local files, but also policies that are
inside of the local storage.
This makes possible to push an upstream policy into a local registry.
Fixes https://github.com/kubewarden/kwctl/issues/41

Extend the `push` command

---

src/main.rs

By calling `kwctl run` with `-r -`, the request can be piped into
kwctl for ease of use.
Fixes https://github.com/kubewarden/kwctl/issues/43

feat: provide request on stdin

---

Cargo.lock
Cargo.toml
src/inspect.rs
src/run.rs

Fixes: https://github.com/kubewarden/kwctl/issues/40
Depends on: https://github.com/kubewarden/policy-evaluator/pull/11

feat: initialize cluster context only if the policy metadata says so

---

src/main.rs
src/manifest.rs

Allow the user to specify the settings to be embedded into the generated manifest.
This is pretty useful, because the user can play with `kwctl run --settings <>` and then, once satisfied, he can feed the same settings into the `manifest` subcommand.

Manifest command: generate settings

---

README.md
src/cli.rs
src/completions.rs
src/main.rs

Add `completions` sub-command. This will generate autocompletion scripts for the major shells, courtesy of clap.
I've also added some instructions to the README about how to use these completion scripts

Completions

---

Cargo.lock
Cargo.toml
src/cli.rs

Fixes: https://github.com/kubewarden/kwctl/issues/64

report supported OPA builtins when `--version` is requested

---

e2e-tests/e2e.bats
src/main.rs

Fix bug when verifying multiple keys in `kwctl {verify, pull, run}`.
Add and fix tests to that effect.
Re-sign image under test.

fix: Verification of multiple keys

---

Cargo.lock
Cargo.toml
src/main.rs
src/run.rs
src/verify.rs

Update to latest release of policy-fetcher and policy-evaluator.
Fix the code to address the breaking changes introduced by the update.

Update dependencies and fix code

---

src/cli.rs
src/main.rs
src/manifest.rs

fixes https://github.com/kubewarden/kwctl/issues/96

Add title to a policy created with kwctl manifest.

---

Cargo.lock
Cargo.toml

This update has to be done at the same time.
This superseeds:
* https://github.com/kubewarden/kwctl/pull/115
* https://github.com/kubewarden/kwctl/pull/115

Update mdcat and pulldown-cmark deps

---

e2e-tests/e2e.bats
src/cli.rs
src/main.rs

fixes https://github.com/kubewarden/kwctl/issues/71

Implement the digest subcommand

---

Cargo.lock
Cargo.toml
src/policies.rs

Bump the policy-fetcher that improves Windows path support on the
policy store.

chore: improve Windows support

---

Cargo.lock
Cargo.toml
src/cli.rs
src/main.rs
src/run.rs

This is a maintenance PR:
- Upgrade clap to latest patch release
- Fix more clippy warnings

fix clippy warnings

---

Cargo.lock
Cargo.toml
src/main.rs
src/policies.rs
src/pull.rs
src/push.rs
src/rm.rs
src/run.rs
src/scaffold.rs
src/utils.rs
src/verify.rs

Depends on: https://github.com/kubewarden/policy-evaluator/pull/108

Consume `policy-fetcher` through `policy-evaluator`

---

Cargo.lock
Cargo.toml
src/cli.rs
src/inspect.rs
src/main.rs

Display Sigstore signatures if available. Do nothing if they are not available.
Generate signatures url simulating the cosign triangulate output. For that we use the manifest digest, which returns the sha256 of the manifest content
Fix #181 
Output example:
```
Details              
title:              psp-capabilities 
description:        Replacement for the Kubernetes Pod Security Policy that controls the usage of capabilities 
author:             Flavio Castelli 
url:                https://github.com/kubewarden/capabilities-psp-policy 
source:             https://github.com/kubewarden/capabilities-psp-policy 
license:            Apache-2.0 
mutating:           true 
context aware:      false 
execution mode:     kubewarden-wapc 
protocol version:   1 
Annotations …
```

feat: show Sigstore signatures on kwctl inspect

---

CHANGELOG.md
CONTRIBUTING.md
Cargo.lock
Cargo.toml
src/main.rs

Bump versions for release.
Fix tracing error.
Bump kube to 0.71.0
Tested manually for tracing warning fix.
I will create tag `0.3.0` once this lands.

Bump for release 0.3.0

---

README.md

feat: Explain how to verify kwctl binaries

---

Cargo.lock
Cargo.toml

Consume the latest stable release

Update to latest release of policy-evaluator

---

Cargo.lock
Cargo.toml

Tag 1.0.0 release

---

Cargo.lock
Cargo.toml

use the latest sigstore-rs that fixes the keyless verification

fix: keyless image verification

---

CHANGELOG.md
Cargo.lock

Bump Changelog, Cargo.lock. Cargo.toml is ready already.
Tested new signature features manually.

Road to 1.1.0

---

CHANGELOG.md
e2e-tests/secure_supply_chain_tests.bats

This will make the e2e-test pass, and by extension, the release build.
Tested manually.

fix: Disable TUF integration test for now

---

.github/workflows/release.yml
.gitignore
Makefile

Adds Makefile target and update the release workflow to generate the SBOM file for the kwctl binaries.
Fix #279

SBOM file generation.

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Prepare v1.3.0-rc1

---

README.md

Adds the OpenSSF badge in the README file.

OpenSSF badge

---

CHANGELOG.md
Cargo.lock
Cargo.toml

e2e tests and manually performed with 1.4.0-rc1 and the new functionalities of yet unreleased verify-image-signatures.

Bump version to 1.4.0

---

Cargo.lock
Cargo.toml

chore: update rust edition

---

README.md

docs: Add Install section to readme

---

README.md

Fix uppercase in readme

---

Cargo.lock
Cargo.toml

- fix: correct parsing of some policy urls
- Tag v1.5.2
This fixes https://github.com/kubewarden/policy-fetcher/issues/131
Once merged, I'll tag a new release

fix airgap links

---

Cargo.lock
Cargo.toml
src/cli.rs
src/inspect.rs
src/main.rs
src/policies.rs
src/run.rs
src/scaffold.rs

This PR adds support of the new context aware feature to kwctl.
Each commit is standalone, and addresses a dedicated issue:
- feat: handle context aware resources attribute - https://github.com/kubewarden/kwctl/issues/427
- fix: better handling of boolean flags
- feat: new context aware implementation - run https://github.com/kubewarden/kwctl/issues/428
- chore(deps): update policy-evaluator dependency
- feat: context aware and scaffold command https://github.com/kubewarden/kwctl/issues/429
Currently the code is built against the `context-aware` feature branch of `policy-evaluator`

Context aware

---

CONTRIBUTING.md

Just some things I noticed when forking kwctl and trying to make a release from the fork.

docs: Document GitHub Action setup on forks

---

Cargo.lock
Cargo.toml

build: Bump version to 1.6.0-rc1

---

Cargo.lock
Cargo.toml
src/scaffold.rs

Prepare for 1.6.0-rc6: update to latest deps and fix a small issue with the unit tests

chore(deps): update to latest deps

---

Cargo.lock
Cargo.toml

Prepare 1.6.0 release

---

.cargo/audit.toml

Remove ignore rules for issues that have been fixed

test: update cargo audit

---

Cargo.toml

Consume correct policy-evaluator.
CI

deps: Consume policy-evaluator v0.11.0

---

Cargo.lock
Cargo.toml

Use latest stable release of policy-evaluator.

chore(deps): update policy-evaluator

---

e2e-tests/e2e.bats

Fixes: #76 
Added e2e test.
Waiting for policy-evaluator bump prior merging

fix: add latest tag when no tag

---

README.md

Unifying README and https://docs.kubewarden.io/security/verifying-kubewarden#kwctl

Update docs to use cosign v2

---

Cargo.lock
Cargo.toml

chore: bump Cargo.toml to v1.8.0-rc2

---

Cargo.lock
Cargo.toml

chore: Bump version to 1.8.0

---

Cargo.lock
Cargo.toml
tests/e2e.rs

build: Bump version to v1.9.0-rc2 

---

tests/data/host-capabilities-sessions/context-aware-unique-ingress-duplicate.yml
tests/data/host-capabilities-sessions/context-aware-unique-ingress-no-duplicate.yml
tests/data/ingress.json
tests/e2e.rs

Test gatekeeper policies making use of context aware data.

test: increase e2e test coverage

---

Cargo.lock
Cargo.toml

Tag 1.9.0-rc3

---

Cargo.lock
Cargo.toml

build: Bump version to v1.9.0

---

Cargo.lock
Cargo.toml

build: Bump version to v1.10.0-rc1

---

Cargo.lock
Cargo.toml
src/backend.rs
src/bench.rs
src/run.rs

Consume latest stable version of policy-evaluator

chore(deps): update to latest version of policy-evaluator

---

Cargo.lock
Cargo.toml

build: Bump version to v1.10.0

---

Cargo.lock
Cargo.toml

Prepare for 1.11.0-rc1 release

Prepare release of 1.11.0-rc1

---

Cargo.lock
Cargo.toml

Prepare for `v1.11.0-rc2`release

chore: bump version to v1.11.0-rc2

---

Cargo.lock
Cargo.toml
src/bench.rs
src/run.rs

bump policy-evaluator version to v0.16.2

build(deps): bump policy-evaluator version to v0.16.2

---

Cargo.lock
Cargo.toml

Updates Cargo files bumping the version to v1.11.0-rc5

chore: bump v1.11.0-rc5.

---

Cargo.lock
Cargo.toml

Tag 1.11-rc6

---

Cargo.lock
Cargo.toml

Updates Cargo.toml to bump the version to v1.11.0.

chore: bump v1.11.0 version.

---

Cargo.lock
Cargo.toml

build(deps): remove unused dependencies

---

Cargo.lock
Cargo.toml

chore: bump version to 1.12.0-rc1

---

Cargo.lock
Cargo.toml

build: Bump version to v1.12.0

---

Cargo.lock
Cargo.toml

Bumps policy evaluator and k8s-openapi to the latest version

build(deps): bump policy-evaluator version to v0.17.2

---

Cargo.lock
Cargo.toml

bump policy-evaluator version to v0.17.3

build(deps): bump policy-evaluator version to v0.17.3

---

Cargo.lock
Cargo.toml

bump policy-evaluator to v0.17.4
bump Cargo.toml to v1.13.0-rc1

chore: prepare to release v1.13.0 rc1

---

Cargo.lock
Cargo.toml

build: Bump version to 1.13.0

---

Cargo.lock
Cargo.toml

build: Bump version to v1.15.0-rc2

---

Cargo.lock
Cargo.toml

build: Bump version to 1.15.0

---

Cargo.lock
Cargo.toml

build: Bump version to 1.16.0-rc1

---

Cargo.lock
Cargo.toml

build: Bump version to 1.16.0-rc2

---

Cargo.lock
Cargo.toml

CI
Once it lands on main, it will get tagged as `1.16.0`.

build: Bump version to 1.16.0

---

Cargo.lock
Cargo.toml

build: Bump version to v1.17.0-rc1

---

Cargo.lock
Cargo.toml

Prepare for v1.17.0-rc2 release

chore: prepare for release v1.17.0-rc2

---

Cargo.lock
Cargo.toml

prepare 1.17.0-rc3

---

Cargo.lock
Cargo.toml

build: Bump to 1.17.0-rc4

---

Cargo.lock
Cargo.toml

Version 1.17.0

---

Cargo.lock
Cargo.toml

chore(deps): bump policy-evaluator

chore(deps): bump policy-evaluator

---

Cargo.lock
Cargo.toml

build: Bump version to 1.18.0-beta1

---

.github/workflows/release.yml

ci: Re-introduce attestation permissions

---

Cargo.lock
Cargo.toml

build: Bump version to v1.18.0-rc1

---

Cargo.lock
Cargo.toml

Relase 1.18.0

---

Cargo.lock
Cargo.toml

Prepare for 1.19.0-beta1 release

---

Cargo.lock
Cargo.toml

Updates the Cargo files bumping the version to v1.19.0-rc1.

chore: bump version v1.19.0-rc1

---

Cargo.lock
Cargo.toml

prepare 1.19.0 release

---

Cargo.lock
Cargo.toml

* Update policy-evaluator dependency
* Bump project version

prepare 1.20.0-rc1

---

Cargo.lock
Cargo.toml

build: Bump version to v1.20.0

---

Cargo.lock
Cargo.toml

Updates policy-evaluator and k8s-openapi dependencies.

chore(deps): updates dependencies.

---

Cargo.lock
Cargo.toml

build: Bump version to v1.21.0-rc1, bump policy-evaluator

---

Cargo.lock
Cargo.toml

prepare for 1.21.0-rc2

---

Cargo.lock
Cargo.toml

Relase 1.21.0

---

Cargo.lock
Cargo.toml

bump policy-evaluator to v0.19.10
prepare to release kwctl 1.21.1

build(deps): bump policy-evaluator to v0.19.10

---

Cargo.lock
Cargo.toml

build: Bump version to 1.22.0-rc1

---

.github/workflows/ci.yml
Makefile
README.md
cli-docs.md
src/backend.rs
src/callback_handler/proxy.rs
src/cli.rs
src/scaffold/manifest.rs
tests/e2e.rs

ci: Add job for `crate-ci/typos` and fix typos on cli docs

---

src/push.rs

A single line terminated by a carriage return caused the resulting manifest to be invalid.
The code now trims the single lines to ensure the resulting annotation is compliant with the OCI standard.
Moreover, the debug message was wrong, it was reporting the annotations to be kept as dropped.

fix: handle single lines terminated by carriage return

---

Cargo.lock
Cargo.toml

Prepare the 1.22.1 patch release

Tag 1.22.1 release

---

Cargo.lock
Cargo.toml

build: Bump version to 1.23.0-beta1

---

tests/e2e.rs

Fix https://github.com/kubewarden/kwctl/issues/308
CI

tests: Use test/cel-policy instead of official one

---

Cargo.lock
Cargo.toml

build: Bump version to 1.23.0-beta2

---

Cargo.lock
Cargo.toml

build: Bump version to 1.23.0

---

Cargo.lock
Cargo.toml

build: Bump version to 1.24.0-rc1

---

Cargo.lock
Cargo.toml

Updates the Cargo files bumping the version to v1.24.0-rc3.

chore: bump version to v1.24.0-rc3.

---

Cargo.lock
Cargo.toml

build: Bump version to 1.24.0

---

src/rm.rs

Fix #537 
- Add version verification before policy removal
- Improve error messages for better user experience
Before -> 
```curl
Error: could not delete policy registry://ghcr.io/kubewarden/policies/disallow-service-loadbalancer: No such file or directory (os error 2)
Or
Error: relative URL without a base
```
After -> 
```
```
```
Error: Cannot find policy with uri: Policy registry://ghcr.io/kubewarden/policies/disallow-service-loadbalancer not found. 
Available versions in local store: latest, v0.1.8
```

feat: Improve policy version handling and verification

---

Cargo.lock
Cargo.toml

build: Bump version to 1.25.0-rc1

---

Cargo.lock
Cargo.toml

Updates the Cargo files to bump version to v1.25.0

chore: v1.25.0 version update

---

src/scaffold/verification_config.rs

docs: Change printed link in `kwctl scaffold verification-config`

---

Cargo.lock
Cargo.toml

build: Bump version to 1.26.0

---

Cargo.toml
src/command/run.rs
src/command/run/evaluator.rs
src/config/policy_definition.rs

Part of https://github.com/kubewarden/kwctl/issues/1272.
CI

feat: Honour policy mode, mutation, custom rejection mesage

---

Cargo.toml

Part of https://github.com/kubewarden/kubewarden-controller/issues/1159

Migrate mailing list mentions to CNCF

---

Cargo.lock
Cargo.toml
src/backend.rs
tests/e2e.rs

Part of https://github.com/kubewarden/kwctl/issues/1290.
Not tested e2e, having trouble building locally.

deps: Consume policy-evaluator 0.29.1

---

Cargo.lock
Cargo.toml

build: Bump version to 1.28.0

---

Cargo.lock
Cargo.toml

build: Bump version to 1.29.0

---

src/scaffold/vap.rs
tests/data/vap/vap-binding-params.yml
tests/data/vap/vap-with-params.yml

Part of https://github.com/kubewarden/cel-policy/issues/161
Added unit test case.

feat!: Implement `vap scaffold vap` for `paramKind`, `paramRef`, `failurePolicy`
